development:
  adapter: postgresql
  encoding: utf8
  database: portfolio-api_development
  pool: 5
  username: wattx
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: portfolio-api_test
  pool: 5
  username: wattx
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: portfolio-api_production
  pool: 5
  username: wattx
  password: